const SECOND   = 1000;
const MINUTE = SECOND * 60;
const HOUR = MINUTE * 60;
const DAY = HOUR * 24;
const WEEK = DAY * 7;
const MONTH = WEEK * 4;
const YEAR = WEEK * 12;

const REFRESH_INTERVAL_LOCAL_STORAGE_KEY = "REFRESH_INTERVAL_LOCAL_STORAGE"

export {
    SECOND,
    MINUTE,
    HOUR,
    DAY,
    WEEK,
    MONTH,
    YEAR,
    REFRESH_INTERVAL_LOCAL_STORAGE_KEY
}
